image: node:19.1.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - npm run export
    - mv public public_old
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
