name: For dev Json Validation and RUN NPX

on:
  push:
    branches:
      - dev
    paths:
      - 'posts/**.json'
      - 'posts/blog/**'
      - 'public/images/blog/**'
      - 'public/basic.png'


permissions:
  contents: write


jobs:
  check-json-updated:
    runs-on: ubuntu-latest

    steps:
      - name: Get list of commits since last push
        id: get_commits
        run: |
          git fetch
          COMMITS=$(git rev-list ${{ github.event.before }}..${{ github.sha }})
          echo "::set-output name=commits::$COMMITS"
      
      - name: Check if specified paths are updated
        id: check_paths
        run: |
          for COMMIT in ${{ steps.get_commits.outputs.commits }}
          do
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $COMMIT)
            for FILE in $FILES_CHANGED
            do
              # ここで指定したパスとマッチするか確認します
              if [[ "$FILE" =~ ^posts/.*\.json$ || "$FILE" =~ ^posts/blog/.* || "$FILE" =~ ^public/images/blog/.* || "$FILE" == 'public/basic.png' ]]; then
                echo "::set-output name=update_required::true"
                break 2
              fi
            done
          done

      - name: Validate and rollback if necessary
        if: steps.check_paths.outputs.update_required == 'true'
        run: |
          VALIDATION_FAILED=false
          for COMMIT in ${{ steps.get_commits.outputs.commits }}
          do
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $COMMIT)
            for FILE in $FILES_CHANGED
            do
              if [[ "$FILE" =~ ^posts/.*\.json$ ]]; then
                # ここでJSONの検証を行います
                if ! cat $FILE | jq empty; then
                  echo "Error: Invalid JSON in $FILE at commit $COMMIT"
                  VALIDATION_FAILED=true
                  break 2
                fi
              fi
            done
          done
      
          if [ "$VALIDATION_FAILED" = true ]; then
            git reset --hard ${{ github.event.before }}
            git push origin HEAD:${{ github.ref }} --force
            exit 1
          fi
      
        
        
        

  run-npx-and-push:
    needs: check-json-updated
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19.1.0"

      - name: Install dependencies
        run: npm install

      - name: Run NPX command
        run: npx ts-node runFunction.ts

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          git commit -m "Automated Update by Github"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/yomogyhub/yomogy_test.git HEAD:dev
