name: JSON Validation

on:
  push:
    branches:
      - dev
    paths:
      - "**/*.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSON
        run: |
          for file in $(find . -name "*.json"); do
            cat $file | jq empty
            if [ $? -ne 0 ]; then
              echo "Invalid JSON in $file"
              exit 1
            fi
          done

      - name: Revert commit on failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git revert HEAD
          git push https://${{ env.GITHUB_TOKEN }}@github.com/your-username/your-repo-name.git HEAD:dev --force
