name: Run NPX

on:
  workflow_run:
    workflows: ["JSON Validation"]
    types:
      - completed

permissions:
  contents: write

jobs:
  check-previous-workflow:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - name: Check if JSON Validation was successful
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "::set-output name=status::failure"
            exit 1
          else
            echo "::set-output name=status::success"
          fi

  run-npx-and-push:
    needs: check-previous-workflow
    if: needs.check-previous-workflow.outputs.status == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19.1.0"

      - name: Install dependencies
        run: npm install

      - name: Run NPX command
        run: npx ts-node runFunction.ts

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          git commit -m "Automated Update by Github"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/yomogyhub/yomogy_test.git HEAD:dev
